// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


void onTestChange();


int test;


void initProperties(){

  
 ArduinoCloud.addProperty(test, Permission::ReadWrite).onUpdate(onTestChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
